version: "3.2"
services:
  web:
    image: cs162-flask
    build: web
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: "on-failure"
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - .:/app

  db:
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "cs162"
      POSTGRES_USER: "cs162_user"
      POSTGRES_PASSWORD: "cs162_password"
    deploy:
      restart_policy:
        condition: "on-failure"
